### ISSUE TITLE
returning "id" - invalid input syntax for json type

### ISSUE THREAD

**Issue by StyvenSoft** [StyvenSoft/add-news#1]
returning "id" - sintaxis de entrada no válida para tipo json
    at Parser.parseErrorMessage (C:\Users\USUARIO\Documents\My Web Sites\add-news\server\node_modules\pg-protocol\dist\parser.js:278:15)
    at Parser.handlePacket (C:\Users\USUARIO\Documents\My Web Sites\add-news\server\node_modules\pg-protocol\dist\parser.js:126:29)
    at Parser.parse (C:\Users\USUARIO\Documents\My Web Sites\add-news\server\node_modules\pg-protocol\dist\parser.js:39:38)
    at Socket.<anonymous> (C:\Users\USUARIO\Documents\My Web Sites\add-news\server\node_modules\pg-protocol\dist\index.js:10:42)
    at Socket.emit (events.js:311:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)

**Comment by StyvenSoft** [comment]
Delete tables from the db, migrations folder and execute command `yarn dev` running the tests:

```
const post = orm.em.create(Post, {title: 'My title'});
await orm.em.persistAndFlush(post);
await orm.em.nativeInsert(Post, {title: 'Second post!'});
```
